"""
Module Manifest: auth
Generated by: aq add module auth --minimal
"""

from aquilia import AppManifest


manifest = AppManifest(
    name="auth",
    version="0.1.0",
    description="Auth module",
    controllers=[
        "modules.auth.controllers:AuthController",
    ],
    services=[],
    middleware=[],
    route_prefix="/auth",
    base_path="modules.auth",
    depends_on=[],
)


__all__ = ["manifest"]