"""
Aquilia Workspace — myapp (minimal)
Generated by: aq init workspace myapp --minimal
"""

from aquilia import Workspace, Module, Integration

workspace = (
    Workspace(
        name="myapp",
        version="0.1.0",
        description="myapp workspace",
    )

    # ---- Modules ---------------------------------------------------------

    .module(Module("products", version="0.1.0", description="Products module")
        .route_prefix("/products")
        .tags("products", "core")
        .register_controllers(
            "modules.products.controllers:ProductsController"
        )
        .register_services(
            "modules.products.services:ProductsService"
        ))

    .module(Module("auth", version="0.1.0", description="Auth module")
        .route_prefix("/auth")
        .register_controllers(
            "modules.auth.controllers:AuthController"
        ))

    .module(Module("users", version="0.1.0", description="Users module")
        .route_prefix("/users")
        .tags("users", "core")
        .register_controllers(
            "modules.users.controllers:UsersController"
        )
        .register_services(
            "modules.users.services:UsersService"
        ))

    # Integrations — core only
    .integrate(Integration.di(auto_wire=True))
    .integrate(Integration.routing(strict_matching=True))
    .integrate(Integration.fault_handling(default_strategy="propagate"))
    .integrate(Integration.patterns())

    # Add modules:
    #   .module(Module("users").route_prefix("/users"))
)

__all__ = ["workspace"]